#define RED_PIN 32
#define YELLOW_PIN 33
#define GREEN_PIN 25
#define BLUE_PIN 25
#define PHOTOSENSOR_PIN 36
#define PHOTOSENSOR_THRESHOLD 1.5
#define HUMIDITY_MEDIUM_THRESHOLD 50
#define HUMIDITY_HIGH_THRESHOLD 70
// #define HUMIDITY_ADDRESS 0x38 // I2C
// #define GYRO_ADDRESS 0x6A     // I2C