#define RED_PIN 32
#define YELLOW_PIN 33
#define GREEN_PIN 25
#define BLUE_PIN 26
#define BUZZER_PIN 2 //?
#define PHOTOSENSOR_PIN 36
#define PHOTOSENSOR_THRESHOLD 2.9
#define HUMIDITY_MEDIUM_THRESHOLD 65
#define HUMIDITY_HIGH_THRESHOLD 85
// #define HUMIDITY_ADDRESS 0x38 // I2C
// #define GYRO_ADDRESS 0x6A     // I2C
#define FALL_FREQUENCY 300
#define GENERAL_FREQUENCY 2000
#define MAX_WEIGHT 150 // grams